### ISSUE TITLE
저장소 네이밍 관련

### ISSUE THREAD

**Issue by namenu** [ridi/ridi-webviewer#1]
1. 리액트 관련 컴포넌트는 통상적으로 `react-` 접두어를 붙이는데, 이를 따르는 것이 어떨까요?
   - 예) https://devarchy.com/react
2. webviewer 모든 기능이 아니므로 client/renderer/component 등의 키워드를 추가하면 좋을 것 같습니다.
   - (실제 서버/클라이언트 통합 저장소명으로 webviewer 가 이미 존재)

**Comment by antiline** [comment]
1. 해당건을 고려를 해봤었는데 redux 도 쓰고 있어서 redux 도 붙여야 할 것 같은데 좀 길지 않나요?
- react-redux-ridi-webviewer-component
2. component 로 하겠습니다.

**Comment by namenu** [comment]
굉장히 길군요..
실제 사용하게될 입장도 한 번 들어보고 싶습니다.

@freekering @kyungmi

**Comment by kyungmi** [comment]
1. 개인적으로는 Redux와 관련된 부분이 단독으로 사용하는 경우가 아니라 React 컴포넌트에 종속적인 경우라면 react-*라는 네이밍이 괜찮을 것 같고요. React 컴포넌트와 상관 없이 단독으로 Redux 데이터 조작만을 위해 따로 사용되는 모듈이 있다면 그 모듈만 따로 레파지토리를 분리해서 redux-*라는 네이밍을 가지는 것이 좋을 것 같습니다.
2. react-*에 컴포넌트라는 의미가 포함되어 있다고 생각합니다. 다른 경우가 있을까요? 아니면 repository에 #component라는 태그 추가를 하는 것도 좋을 것 같아요.

**Comment by antiline** [comment]
@Jaeyo 님은 어떻게 생각하시나요?

**Comment by Jaeyo** [comment]
1. 추후에 redux 관련된 부분을 외부 인터페이스로 드러내지 않도록 하는 부분으로의 리팩토링을 생각하고 있어서 굳이 redux-* 접두어는 필요없지 않나 하는 생각입니다. 

2. 관례로 볼때나, react 에 종속적인 부분으로 볼 때나 react-* 접두어를 붙이는 부분은 찬성합니다.

3. 소스 내부에서 ViewerScreen 컴포넌트를 export default 하고 있기 때문에 screen 이라는 단어를 붙이는 것도 좋겠다는 생각이 드네요. (ex. react-ridi-webviewer-screen)

**Comment by namenu** [comment]
`react-` 가 component 개념을 포함한다는 말에 동의합니다.
그렇게 생각해보니 UI 개념을 포함하고 있기 때문에 접미어는 없어도 되지 않을까 싶습니다.

@antiline `react-ridi-webviewer` 정도로 정리하면 좋겠습니다.
